export interface AppErrorResponse {
  code: ErrorCode;
  statusCode: number;
  message: string;
  reason?: string;
}

export enum ErrorCode {
  UNKNOWN_ERROR = "UNKNOWN_ERROR",

  BAD_REQUEST = "BAD_REQUEST",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",

  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  SESSION_EXPIRED = "SESSION_EXPIRED",

  DATABASE_ERROR = "DATABASE_ERROR",
  DATABASE_UNIQUE_CONSTRAINT = "DATABASE_UNIQUE_CONSTRAINT",
  DATABASE_NOT_FOUND = "DATABASE_NOT_FOUND",
  DATABASE_FOREIGN_KEY = "DATABASE_FOREIGN_KEY",

  WS_CONNECTION_REJECTED = "WS_CONNECTION_REJECTED",
}
